import fs from 'node:fs/promises';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
import {optimize} from 'svgo';
import sharp from 'sharp';
const dir='src/assets/mascot',temp='artifacts/mascot/generator',raw='artifacts/mascot/raw';
await fs.mkdir(temp,{recursive:true});await fs.mkdir(raw,{recursive:true});
for(const file of ['m1.js','build.js','package.json'])await fs.copyFile(`${dir}/source/${file}`,`${temp}/${file}`);
execFileSync(process.execPath,['build.js',path.resolve(raw)],{cwd:temp,stdio:'pipe'});
const rules=new Map();
function classForTransform(value){
 if(!rules.has(value)){
  const name=`m1-transform-${rules.size}`;let css;
  const rotation=value.match(/^rotate\(([-.\d]+) ([-.\d]+) ([-.\d]+)\)$/),translation=value.match(/^translate\(([-.\d]+) ([-.\d]+)\)$/);
  if(rotation)css=`transform:rotate(${rotation[1]}deg);transform-origin:${rotation[2]}px ${rotation[3]}px;transform-box:view-box`;
  else if(translation)css=`transform:translate(${translation[1]}px,${translation[2]}px);transform-box:view-box`;
  else throw Error(`Unexpected generator transform: ${value}`);
  rules.set(value,{name,css});
 }return rules.get(value).name;
}
const opacityClass={'.55':'m1-far','.14':'m1-beam-fill'};
const plugin={name:'mule-csp',fn:()=>({element:{enter(node){
 const a=node.attributes,classes=(a.class||'').split(' ').filter(Boolean);
 if(a.id)classes.push(`m1-${a.id}`);
 if(a.opacity){if(!opacityClass[a.opacity])throw Error(`Unknown opacity ${a.opacity}`);classes.push(opacityClass[a.opacity]);delete a.opacity;}
 if(a.transform){classes.push(classForTransform(a.transform));delete a.transform;}
 if(classes.length)a.class=[...new Set(classes)].join(' ');
}}})};
const poses={},rasterPoses={};
for(const file of (await fs.readdir(raw)).filter(f=>f.endsWith('.svg')).sort()){
 const source=await fs.readFile(`${raw}/${file}`,'utf8');
 if(/unit-m1-pose-(delivered|refuse)\.svg/.test(file))rasterPoses[file.slice(13,-4)]=source.replace(/^<svg[^>]*>/,'').replace(/<\/svg>$/,'');
 const data=optimize(source,{plugins:[plugin,'removeDoctype','removeXMLProcInst','removeComments','removeMetadata','cleanupAttrs','sortAttrs']}).data;
 await fs.writeFile(`${dir}/${file}`,data+'\n');
 if(file.startsWith('unit-m1-pose-'))poses[file.slice(13,-4)]=data.replace(/^<svg[^>]*>/,'').replace(/<\/svg>$/,'');
}
await fs.writeFile(`${dir}/raster-poses.mjs`,'// Private rendering input for OG PNGs; never inserted into HTML.\nexport const rasterPoses = '+JSON.stringify(rasterPoses)+';\n');
const css='/* Generated from the approved SVG transforms. Do not edit geometry. */\n.m1-far{opacity:.55}\n.m1-beam-fill{opacity:.14}\n'+[...rules.values()].map(({name,css})=>`.${name}{${css}}`).join('\n')+'\n';
await fs.writeFile(`${dir}/poses.css`,css);await fs.writeFile('public/brand/mascot-poses.css',css);
await fs.writeFile(`${dir}/generated.mjs`,'// Generated by scripts/build-mascot.mjs from the approved generator.\nexport const poses = '+JSON.stringify(poses)+';\n');
// Raster exports use the original SVG with its presentation attributes; no redesign or filters.
for(const pose of ['delivered','refuse']){
 const svg=(await fs.readFile(`${raw}/unit-m1-pose-${pose}.svg`,'utf8')).replace('viewBox="0 0 300 240"','viewBox="40 -30 260 270"').replace('width="300" height="240"','width="520" height="540"');
 await sharp(Buffer.from(svg)).png().toFile(`${dir}/patch-${pose}.png`);
}
const favicon=await fs.readFile(`${dir}/unit-m1-favicon.svg`,'utf8');await fs.writeFile('public/brand/mule-favicon.svg',favicon);
for(const size of [32,180,192,512])await sharp(`${raw}/unit-m1-favicon.svg`,{density:768}).resize(size,size).png().toFile(`public/brand/icon-${size}.png`);
console.log(`Prepared ${Object.keys(poses).length} approved poses; ${rules.size} CSS transforms; raster icons and patches.`);